CREATE TABLE Movie(
ID VARCHAR(20),
TITLE VARCHAR(200),
YEAR INT,
RELEASED VARCHAR(15),
RUNTIME INT,
RATED VARCHAR(10),
IMDBVOTES INT,
IMDBAVG NUMERIC(2,1),
PRIMARY KEY (ID)
);

CREATE TABLE MoviePlot(
MOVIE_ID VARCHAR(20) NOT NULL,
Plot VARCHAR(300)
);

CREATE TABLE Genre(
MOVIE_ID VARCHAR(20) NOT NULL,
GENRE_TYPE VARCHAR(20)
);

CREATE TABLE Director(
MOVIE_ID VARCHAR(20) NOT NULL,
NAME VARCHAR(30)
);

CREATE TABLE ReleasedIn(
MOVIE_ID VARCHAR(20) NOT NULL,
COUNTRY VARCHAR(15)
);

CREATE TABLE Actor(
MOVIE_ID VARCHAR(20) NOT NULL,
NAME VARCHAR(30)
);

CREATE TABLE BoxOffice(
MOVIE_ID VARCHAR(20) NOT NULL,
EARNINGS INT
);

CREATE TABLE CriticRatings(
MOVIE_ID VARCHAR(20) NOT NULL,
METASCORE INT,
ROTTENTOMATOES INT
);

CREATE TABLE Awards(
MOVIE_ID VARCHAR(20) NOT NULL,
OSCARS INT,
WINS INT,
NOMINATIONS INT
);

CREATE TABLE users (
username VARCHAR(20),
password VARCHAR(20),
isAdmin NUMBER(1) NOT NULL CHECK  (isAdmin in (0,1))
);

INSERT INTO users VALUES ('Admin', 'Admin', 1);